language: php
sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 7.0
  - hhvm

env:
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.*
  - SYMFONY_VERSION=^3.1@dev

before_install:
  - composer self-update

install:
  - composer require symfony/symfony:${SYMFONY_VERSION}

notifications:
  email:
    - piku235@gmail.com

matrix:
  exlude:
    - php: 5.3
      env: SYMFONY_VERSION=3.0.*
    - php: 5.4
      env: SYMFONY_VERSION=3.0.*
    - php: 5.3
      env: SYMFONY_VERSION=^3.1@dev
    - php: 5.4
      env: SYMFONY_VERSION=^3.1@dev
  allow_failures:
    - php: hhvm
    - env: SYMFONY_VERSION=^3.1@dev
