language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

env:
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*

install:
  - composer require symfony/symfony:${SYMFONY_VERSION}

notifications:
  email:
    - piku235@gmail.com

matrix:
  allow_failures:
    - php: hhvm
